apiVersion: v1
kind: Service
metadata:
  name: kafka-external
  namespace: video-processing
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: kafka-external
  namespace: video-processing
subsets:
- addresses:
  - ip: 172.21.0.4  # IP direto do Kafka na rede Docker
  ports:
  - port: 9092
    protocol: TCP